disallowed-methods = [
    { path = "tokio::task::spawn", reason = "To provide cancel-safety, use `SpawnedTask::spawn` instead (https://github.com/apache/datafusion/issues/6513)" },
    { path = "tokio::task::spawn_blocking", reason = "To provide cancel-safety, use `SpawnedTask::spawn_blocking` instead (https://github.com/apache/datafusion/issues/6513)" },

    # use the faster & simpler non-poisonable primitives in `parking_lot` instead
    "std::sync::Mutex::new",
    "std::sync::RwLock::new",
    "std::sync::Condvar::new",

    # use std instead
    "once_cell::sync::Lazy::new",

    # use builtin join_unwind instead
    "tokio::task::JoinSet::join_next",
    "tokio::task::JoinSet::join_next_with_id",
]
# TODO: Enable
# disallowed-types = [
#     { path = "std::time::Instant", reason = "Use `datafusion_common::instant::Instant` instead for WASM compatibility" },
# ]

# Lowering the threshold to help prevent stack overflows (default is 16384)
# See: https://rust-lang.github.io/rust-clippy/master/index.html#/large_futures
future-size-threshold = 10000

allowed-wildcard-imports = [
    "arrow",
    "constants",
    "datatypes",
    "deserialize",
    "errors",
    "params",
    "serialize",
    "super",
    "tracing",
    "types",
]
